### ISSUE TITLE
trigger conditions correct?

### ISSUE THREAD

**Issue by tmIdiada** [asam-oss/OSC-ALKS-scenarios#43]
Hi,

if I understand you correctly, then you are focusing on xosc v1.1 instead of v1.0.
If so, then you should use for many triggers lessOrEqual instead of lessThan (e.g. distances) and greaterOrEqual instead of greaterThan (e.g. start time). What do you mean?

Kind regards,

Thaddäus

**Comment by arauschert** [comment]
You're absolutely right. With OpenSCENARIO 1.1 it's now possible to use lessOrEqual and greaterOrEqual, which would trigger the actions more precisely. I will update this.
