### ISSUE TITLE
Lane ID parameters need to be of type integer

### ISSUE THREAD

**Issue by arauschert** [asam-oss/OSC-ALKS-scenarios#49]
in the parameter declaraions for some scenarios lane IDs are defined. In their usage they need to be strings, but this doesn't work for constraints (e.g. 3 < LaneId < 5). Therefore the parameters should be defined as integer, so they can be used for checking constraints and within expressions. They would need to be implicitly converted to a string when they are used as string attribute for a laneID

**Comment by frazar** [comment]
Isn't the lane ID defined as a `String` in the [specification](https://www.asam.net/static_downloads/ASAM_OpenSCENARIO_V1.2.0_Model_Documentation/modelDocumentation/content/LanePosition.html)?
![image](https://github.com/asam-oss/OSC-ALKS-scenarios/assets/914950/a601f3b2-8e25-4c02-bdd1-0358dd6d8464)

Another option to achieve validation of the constraint could be to have a series of Constraint Groups. For example, for allowing only lane IDs between -3 and -5:
```xml
    <ParameterDeclaration name="Ego_InitPosition_LaneId" parameterType="string" value="-4">
      <ConstraintGroup>
        <ValueConstraint rule="equalTo" value="-5" />"
      </ConstraintGroup>
      <ConstraintGroup>
        <ValueConstraint rule="equalTo" value="-4" />"
      </ConstraintGroup>
      <ConstraintGroup>
        <ValueConstraint rule="equalTo" value="-3" />"
      </ConstraintGroup>
    </ParameterDeclaration>
```
