### ISSUE TITLE
XML validation failed

### ISSUE THREAD

**Issue by jasonxzzhang** [asam-oss/OSC-ALKS-scenarios#52]
Hi I tried to execute the supported osc files in Carla 0.9.11 (same version for scenario runner), however the xmlschema validator is throwing back errors. I tried the 4.1.1 (free driving scenario), and get an error at this first instance (I think there could be more incompatibility later on the osc file as well)

```
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating <Element 'ParameterDeclaration' at 0x7f54c24c36b0> with XsdElement(name='ParameterDeclaration', occurs=[0, None]):

Reason: character data is not allowed because the type's content is empty

Schema:

  <xsd:element xmlns:xsd="http://www.w3.org/2001/XMLSchema" maxOccurs="unbounded" minOccurs="0" name="ParameterDeclaration" type="ParameterDeclaration" />

Instance:

  <ParameterDeclaration name="Ego_InitSpeed_Ve0_kph" parameterType="double" value="60.0">
    <ConstraintGroup>
      
      <ValueConstraint rule="greaterThan" value="0.0" />
      <ValueConstraint rule="lessOrEqual" value="60.0" />
    </ConstraintGroup>
  </ParameterDeclaration>
```

**Comment by arauschert** [comment]
Thanks for pointing this out. It seems some xsd validators have issues with the comments in the xml files. We will verify this and update the scenarios accordingly.
Meanwhile you can try to remove the comments from the files and see if this works.

**Comment by jasonxzzhang** [comment]
> Thanks for pointing this out. It seems some xsd validators have issues with comments at specific places in the xml files. We will verify this and update the scenarios accordingly. Meanwhile you can try to remove the comments from the files and see if this works.

Thank you for your reply, please let me know the outcome. I will try removing the comments as well in the meantime
