### ISSUE TITLE
Change LICENSE

### ISSUE THREAD

**Issue by jdsika** [asam-oss/OSC-ALKS-scenarios#63]
We should consider to change this LICENSE to MPL 2.0

**Comment by jdsika** [comment]
@jakobkaths and @eknabevcc I would need your consent for this as contributors.

**Comment by jakobkaths** [comment]
Just out of curiosity: what is the reason for changing the license, @jdsika ?

**Comment by jakobkaths** [comment]
I thought, copyright and patent issues were somewhat separate. But in any case, I'm okay with changing the license, which was your original question.

**Comment by jdsika** [comment]
yes, you are absolutely right. CC-BY is only applying to copyright and excludes all possible patent rights. If you read the MPL 2.0 then you can see that patent rights are licensed if it is needed for the program

**Comment by eknabevcc** [comment]
Totally OK from my and esmini side. Perfectly compatible with esmini which also have MPL 2.0 👍
