### ISSUE TITLE
Suggestion: Move 'Catalogs' folder inside 'Scenarios' folder

### ISSUE THREAD

**Issue by fraprue** [asam-oss/OSC-ALKS-scenarios#65]
Hi.
We were wondering if the catalogs should move one level below in the folder structure. The rationale beind this, that right now most scenarios contain a line like `<Directory path="../Catalogs/Vehicles" />`, i.e. when resolving all necessary paths starting from the scenario, you need to go up one level in your local folder structure.

This can be annoying, as the scenario is typically the first-level entrypoint for most tools, so it usually already resides on the highest level in the respective working directory. With the current structure, the user of this repo would then either need to put their catalogs outside of the working dir, or they need to adapt every scenario file accordingly.

Maps, as another dependency of the scenarios, are already on the same level as the scenarios, so we are curious why the catalogs are being treated differently.

Thanks for your help!

**Comment by arauschert** [comment]
Hi Frank! 
Thanks for your proposal. You're right, the folder structure could be improved. Would be good, if all references point to files in the same directory or below.
The maps should also be put into a separate folder. 
I will create a corresponding MR.

**Comment by arauschert** [comment]
What do you think about the following proposal?

- LogicalScenarios
  - variation1.xosc
  - variation2.xosc
  ...
  - ConcreteScenarios
    - scenario1.xosc
    - scenario2.xosc
    ...
    - Catalogs
      - Vehicles
      - MiscObjects
      ...
    - Maps
      - map1.xodr
      - map2.xodr
      ...

**Comment by fraprue** [comment]
To me your proposal makes sense, especially since it promotes the LogicalScenarios (they seemed a bit hidden before).
Also, putting all maps in a dedicated folder should make things clearer.
Thanks for coming back on such short notice!
